### ISSUE TITLE
Split wireframes into React components

### ISSUE THREAD

**Issue by marcus-crane** [piro-inc/piro#13]
Boxification of our wireframes

**Comment by rich-farr** [comment]
Home/Splash Page: `<Home />`
`<Options />` ||  `<Credentials />` (these are swapped out if we're on splash or login/register pages)

**Comment by rich-farr** [comment]
Game Summary Page: `<Navbar />`
`<Preview />` (multiple; one for each game shown on the page).

**Comment by rich-farr** [comment]
Create Page: `<Navbar />`, `<Create />` (uses HTML form)

**Comment by rich-farr** [comment]
Game Detail Page: `<Navbar />`
`<Game />`
Children:`<Score />` (x2, one for each team),`<Comments />`.

**Comment by rich-farr** [comment]
Console Page: `<Navbar />`, `<Console />` (uses HTML form).

**Comment by rich-farr** [comment]
And of course we need `<App />`!

**Comment by rich-farr** [comment]
Link to pic of whiteboard on Slack https://files.slack.com/files-tmb/T02SQPVAC-F1VTC37KN-2bb75a629b/imag0762_720.jpg
